const spielerNamen = {
  spieler: [
    'Captain Quirk',
    'Sir Pranksalot',
    'The Jokester',
    'Mad Hatter',
    'Dame Dazzle',
    'Baron von Fun',
    'The Punderful Wizard',
    'The Chuckle Champion',
    'Lady Giggles',
    'Mister Witty',
    'Count Funnybone',
    'The Laughing Ninja',
    'Doctor Jester',
    'The Smirk Master',
    'Silly Professor',
    'The Whimsical Wonder',
    'The Jestful Joker',
    'Duchess of Laughter',
    'Master Gigglefit',
    'The Grin Reaper',
  ],
};
