const spielerNamen = {
  spieler: [
    'The Jokester',
    'Mad Hatter',
    'Dame Dazzle',
    'Baron von Fun',
    'The Punderful Wizard',
    'The Chuckle Champion',
    'Lady Giggles',
    'Mister Witty',
    'Count Funnybone',
    'The Laughing Ninja',
    'Doctor Jester',
    'The Smirk Master',
    'Silly Professor',
    'The Whimsical Wonder',
    'The Jestful Joker',
    'Duchess of Laughter',
    'Master Gigglefit',
    'The Grin Reaper',
    'The Great Zucchini',
    'Captain Quack',
    'Sir Wigglesworth',
    'Baroness Fizzypop',
    'Doctor McTickles',
    'Countess Gigglesnort',
    'Duke Snickerdoodle',
    'Madame Bubblegum',
    'Mr. Chucklebottom',
    'Colonel Bumblebee',
    'Lady Tickleton',
    'General Noodlehead',
    'Sergeant Snickerdoodle',
    'Mister Giggles',
    'Doctor Bumblebee',
    'The Laughing Llama',
    'Captain Gigglesworth',
    'The Silly Sausage',
    'Sir Chuckles',
    'The Merry Munchkin',
    'Baroness Giggles',
    'Doctor Quirk',
    'Lady Wobblebottom',
    'Mister Wiggles',
    'The Giggling Gazelle',
    'Colonel Snort',
    'Sergeant Quackers',
    'The Silly Sprite',
    'Madame Chuckleberry',
    'General Gigglepants',
    'Count Tickles-a-Lot',
    'Lady Bumblebutt',
    'The Laughing Lark',
    'Sir Gigglesworth',
    'Captain Quirkypants',
    'The Silly Monkey',
    'Doctor Chucklefritz',
    'Baron Von Guffaw',
    'Madame Snickerdoodle',
    'Mister Guffaw',
    'Lady Wigglesworth',
    'The Merry Minstrel',
    'Colonel Quack-a-Lot',
    'Sergeant Tickles',
    'The Silly Snail',
    'General Gigglesnort',
    'Countess Quirk',
    'The Laughing Lizard',
    'Sir Snort',
    'Captain Quirky',
    'The Silly Seal',
    'Doctor Snickerdoodle',
    'Baroness Guffaw',
    'Mister Chuckleberry',
    'Lady Gigglepants',
    'The Merry Magician',
    'Colonel Gigglesworth',
    'Sergeant Quirk-a-Lot',
    'The Silly Shark',
    'Madame Snort',
    'General Quackers',
    'Countess Tickles',
    'Doctor Wobblebottom',
    'Lady Guffaw',
    'The Laughing Lion',
    'Sir Chuckles-a-Lot',
    'Captain Giggly',
    'The Silly Sloth',
    'Baron Von Snickerdoodle',
    'Madame Gigglesnort',
    'Mister Quirk',
    'Colonel Wobblebutt',
    'Lady Chuckleberry',
    'General Snickerdoodle',
    'Sergeant Guffaw',
    'The Silly Swan',
  ],
};
